In [8]:
import pandas as pd

In [10]:
uberdata=pd.read_csv("D:/Downloads (Brave)/Lab/csv/uber.csv")

In [25]:
uberdata.head()

Unnamed: 0                            key  fare_amount  \
0    24238194    2015-05-07 19:52:06.0000003          7.5   
1    27835199    2009-07-17 20:04:56.0000002          7.7   
2    44984355   2009-08-24 21:45:00.00000061         12.9   
3    25894730    2009-06-26 08:22:21.0000001          5.3   
4    17610152  2014-08-28 17:47:00.000000188         16.0   

            pickup_datetime  pickup_longitude  pickup_latitude  \
0 2015-05-07 19:52:06+00:00        -73.999817        40.738354   
1 2009-07-17 20:04:56+00:00        -73.994355        40.728225   
2 2009-08-24 21:45:00+00:00        -74.005043        40.740770   
3 2009-06-26 08:22:21+00:00        -73.976124        40.790844   
4 2014-08-28 17:47:00+00:00        -73.925023        40.744085   

   dropoff_longitude  dropoff_latitude  passenger_count  
0         -73.999512         40.723217                1  
1         -73.994710         40.750325                1  
2         -73.962565         40.772647                1  
3         -73.965316         40.803349                3  
4         -73.973082         40.761247                5

In [12]:
uberdata.describe

<bound method NDFrame.describe of         Unnamed: 0                            key  fare_amount  \
0         24238194    2015-05-07 19:52:06.0000003          7.5   
1         27835199    2009-07-17 20:04:56.0000002          7.7   
2         44984355   2009-08-24 21:45:00.00000061         12.9   
3         25894730    2009-06-26 08:22:21.0000001          5.3   
4         17610152  2014-08-28 17:47:00.000000188         16.0   
...            ...                            ...          ...   
199995    42598914   2012-10-28 10:49:00.00000053          3.0   
199996    16382965    2014-03-14 01:09:00.0000008          7.5   
199997    27804658   2009-06-29 00:42:00.00000078         30.9   
199998    20259894    2015-05-20 14:56:25.0000004         14.5   
199999    11951496   2010-05-15 04:08:00.00000076         14.1   

                pickup_datetime  pickup_longitude  pickup_latitude  \
0       2015-05-07 19:52:06 UTC        -73.999817        40.738354   
1       2009-07-17 20:04:56 UTC  

In [15]:
uberdata.shape

(200000, 9)

In [16]:
uberdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 9 columns):
 #   Column             Non-Null Count   Dtype  
---  ------             --------------   -----  
 0   Unnamed: 0         200000 non-null  int64  
 1   key                200000 non-null  object 
 2   fare_amount        200000 non-null  float64
 3   pickup_datetime    200000 non-null  object 
 4   pickup_longitude   200000 non-null  float64
 5   pickup_latitude    200000 non-null  float64
 6   dropoff_longitude  199999 non-null  float64
 7   dropoff_latitude   199999 non-null  float64
 8   passenger_count    200000 non-null  int64  
dtypes: float64(5), int64(2), object(2)
memory usage: 13.7+ MB


In [19]:
df=uberdata.drop(columns=['Unnamed: 0', 'key', 'pickup_datetime'])
df

fare_amount  pickup_longitude  pickup_latitude  dropoff_longitude  \
0               7.5        -73.999817        40.738354         -73.999512   
1               7.7        -73.994355        40.728225         -73.994710   
2              12.9        -74.005043        40.740770         -73.962565   
3               5.3        -73.976124        40.790844         -73.965316   
4              16.0        -73.925023        40.744085         -73.973082   
...             ...               ...              ...                ...   
199995          3.0        -73.987042        40.739367         -73.986525   
199996          7.5        -73.984722        40.736837         -74.006672   
199997         30.9        -73.986017        40.756487         -73.858957   
199998         14.5        -73.997124        40.725452         -73.983215   
199999         14.1        -73.984395        40.720077         -73.985508   

        dropoff_latitude  passenger_count  
0              40.723217                1  
1              40.750325                1  
2              40.772647                1  
3              40.803349                3  
4              40.761247                5  
...                  ...              ...  
199995         40.740297                1  
199996         40.739620                1  
199997         40.692588                2  
199998         40.695415                1  
199999         40.768793                1  

[200000 rows x 6 columns]

In [26]:
# uber_data['pickup_datetime']=pd.to_datetime(uber_data['pickup_datetime'])
# uber_data

In [28]:
uberdata.isnull().sum()

Unnamed: 0           0
key                  0
fare_amount          0
pickup_datetime      0
pickup_longitude     0
pickup_latitude      0
dropoff_longitude    1
dropoff_latitude     1
passenger_count      0
dtype: int64

In [31]:
uberdata.isna().sum()

Unnamed: 0           0
key                  0
fare_amount          0
pickup_datetime      0
pickup_longitude     0
pickup_latitude      0
dropoff_longitude    1
dropoff_latitude     1
passenger_count      0
dtype: int64

In [33]:
from sklearn.impute import SimpleImputer

In [36]:
imputer=SimpleImputer(strategy='mean')
df_imputed=pd.DataFrame(imputer.fit_transform(df), columns=df.columns)
df_imputed

fare_amount  pickup_longitude  pickup_latitude  dropoff_longitude  \
0               7.5        -73.999817        40.738354         -73.999512   
1               7.7        -73.994355        40.728225         -73.994710   
2              12.9        -74.005043        40.740770         -73.962565   
3               5.3        -73.976124        40.790844         -73.965316   
4              16.0        -73.925023        40.744085         -73.973082   
...             ...               ...              ...                ...   
199995          3.0        -73.987042        40.739367         -73.986525   
199996          7.5        -73.984722        40.736837         -74.006672   
199997         30.9        -73.986017        40.756487         -73.858957   
199998         14.5        -73.997124        40.725452         -73.983215   
199999         14.1        -73.984395        40.720077         -73.985508   

        dropoff_latitude  passenger_count  
0              40.723217              1.0  
1              40.750325              1.0  
2              40.772647              1.0  
3              40.803349              3.0  
4              40.761247              5.0  
...                  ...              ...  
199995         40.740297              1.0  
199996         40.739620              1.0  
199997         40.692588              2.0  
199998         40.695415              1.0  
199999         40.768793              1.0  

[200000 rows x 6 columns]

In [37]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression, Ridge, Lasso

In [38]:
X=df_imputed.drop(columns=['fare_amount'])
y=df_imputed['fare_amount']

In [39]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=49)

In [40]:
X_train

pickup_longitude  pickup_latitude  dropoff_longitude  \
147339        -73.981132        40.758117         -73.971655   
186079        -73.964417        40.791611         -73.949440   
45515         -73.948633        40.773925         -74.002012   
198640        -73.978347        40.752450         -74.001210   
85902         -73.969802        40.762361         -73.990361   
...                  ...              ...                ...   
7924          -73.960800        40.757179         -73.967583   
19638         -73.970990        40.761995         -73.983042   
81397         -73.956771        40.713491         -73.963798   
186029        -73.964205        40.807132         -73.965955   
426           -74.003558        40.726427         -73.981793   

        dropoff_latitude  passenger_count  
147339         40.756437              5.0  
186079         40.781891              1.0  
45515          40.715360              1.0  
198640         40.746592              3.0  
85902          40.731694              1.0  
...                  ...              ...  
7924           40.755348              3.0  
19638          40.771363              1.0  
81397          40.673046              1.0  
186029         40.799478              5.0  
426            40.757147              5.0  

[160000 rows x 5 columns]

In [42]:
y_test

75162      7.0
196740     5.0
123556    21.0
26664      5.7
167204     5.5
          ... 
8722      10.5
7693       6.1
16602      7.0
121029    10.1
112920     3.7
Name: fare_amount, Length: 40000, dtype: float64

In [43]:
scaler=StandardScaler()

In [44]:
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.fit_transform(X_test)

In [52]:
X_test_scaled.shape

(40000, 5)

In [55]:
import numpy as np

In [62]:
#ImplementLinearRegression
lr_model=LinearRegression()
lr_model.fit(X_train_scaled, y_train)
y_pred_lr=lr_model.predict(X_test_scaled)
y_pred_lr

array([11.69942513, 11.27522683, 11.27722902, ..., 11.44541033,
       11.44476636, 11.27685838])

In [64]:
#ImplementRidgeRegression
ridge_model=Ridge(alpha=1.0)
ridge_model.fit(X_train_scaled, y_train)
y_pred_ridge=ridge_model.predict(X_test_scaled)
y_pred_ridge

array([11.69942292, 11.27522736, 11.2772294 , ..., 11.44540972,
       11.44476579, 11.27685877])

In [66]:
#ImplementLassoRegression
lasso_model=Lasso(alpha=0.1)
lasso_model.fit(X_train_scaled, y_train)
y_pred_lasso=lasso_model.predict(X_test_scaled)
y_pred_lasso

array([11.38192251, 11.34087537, 11.34087537, ..., 11.35729423,
       11.35729423, 11.34087537])

In [67]:
from sklearn.metrics import r2_score, mean_squared_error

In [68]:
def evaluate_model(y_true, y_pred, model_name):
    r2=r2_score(y_true, y_pred)
    rmse=np.sqrt(mean_squared_error(y_true, y_pred))
    print(f"{model_name} - R2 Score: {r2:4f}, RMSE: {rmse:2f}")

In [69]:
evaluate_model(y_test, y_pred_lr, "Linear Regression")

Linear Regression - R2 Score: 0.000225, RMSE: 9.859419


In [70]:
evaluate_model(y_test, y_pred_ridge, "Ridge Regression")

Ridge Regression - R2 Score: 0.000225, RMSE: 9.859419


In [71]:
evaluate_model(y_test, y_pred_lasso, "Lasso Regression")

Lasso Regression - R2 Score: -0.000035, RMSE: 9.860701
